---
title: "Schedule"
---

+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6th February | **Title**                                                          | **Topics covered**                                                                            | **Essential reading**                                                                                                                                                    |
+:=============+:===================================================================+:==============================================================================================+:=========================================================================================================================================================================+
| 9:00- 10:30  | Software                                                           | Objectives of the workshop:Importance of Research Design, R, STATA, gituhub basic environment | [STATA](https://www.stata.com/) [RStudio cloud](rstudio.cloud) [github](github.com) [Quarto](quarto.pub)                                                                 |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30-11:00  | Tea , Networking                                                   |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00-12:45  | Short Panel                                                        | Micro-panel data concepts and applications                                                    | [Application](https://zahidasghar.com/econometrics/Panel_reg)                                                                                                            |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:45-13:30  | Lunch-Prayer Break                                                 |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:30-15:00  | Difference in differences approach                                 | Concepts and practice                                                                         | [Card-Krueger paper replication in STATA and R](https://davidcard.berkeley.edu/papers/njmin-aer.pdf)                                                                     |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:15-16:45  | Hands on Practice with data on health insurance subsidy program    |                                                                                               | \[HISP [Impact Evaluation in Practice - Second Edition (worldbank.org)](https://www.worldbank.org/en/programs/sief-trust-fund/publication/impact-evaluation-in-practice) |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7th February |                                                                    |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:00-10:30   | Re-cap of Day-1, Instrumental Variable                             | Instrumental Variables                                                                        | Slides from [Andrew Heiss](andrewheiss.com)                                                                                                                              |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30-11:00  | Tea-break and queries of participants                              |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00-12:45  | Instrumental Variable regression                                   | IV 3 assumptions, Endogeneity/Exogeneity, Causal Inference                                    | [Angrist-Krueger Paper Replication in STATA and R](https://www.jstor.org/stable/2937954#metadata_info_tab_contents)                                                      |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:45-13:30  | Lunch and Prayer Break                                             |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:30-15:30  | Regression Discontinuity Design and PSM concepts with Applications |                                                                                               | Slides and application with Health Insurance Subsidy Program                                                                                                             |
|              |                                                                    |                                                                                               |                                                                                                                                                                          |
|              | Lab Session                                                        |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:30-17:00  | Hands on practice, Way-forward                                     |                                                                                               |                                                                                                                                                                          |
|              |                                                                    |                                                                                               |                                                                                                                                                                          |
|              | Certificate Distribution                                           |                                                                                               |                                                                                                                                                                          |
+--------------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
